# Generated by Django 4.2.6 on 2024-02-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
